### PR TITLE
Update server to debian buster

### PR DESCRIPTION
**Pull request by gidsi**
New debian stable is out for a few month now :)

### CODE REVIEW

**Comment by dbrgn** [comment]
Don't we have to update our ansible config at the same time? I'm sure some small details changed.

**Comment by gidsi** [comment]
@dbrgn thought so too. I've tested it against the dev environment and everything looks fine (machine is going to be destroyed and recreated, we don't need to do a dist upgrade)

**Comment by dbrgn** [comment]
Ok, nice :slightly_smiling_face: The advantage of running services inside Docker, and using `{{ ansible_distribution_release }}` :slightly_smiling_face:

**Comment by dbrgn** [comment]
Do we need to migrate any data?

**Comment by gidsi** [comment]
Yeah, exactly :)

We don't need to migrate anything, the important volume is detached from the node itself (all data that we need in some way is on there) and gets automatically connected to the new node via Terraform :)

**Pull request merged**
