### PR TITLE
validator: Add role

### PR DESCRIPTION
**Pull request by dbrgn**
https://validator.spaceapi.io/v1/

### CODE REVIEW

**Comment by dbrgn** [comment]
How do I set CORS headers in Traefik, @gidsi? (`Access-Control-Allow-Origin: *`)

**Comment by gidsi** [comment]
> How do I set CORS headers in Traefik, @gidsi? (`Access-Control-Allow-Origin: *`)

You can find them here:
https://docs.traefik.io/configuration/backends/docker/#security-headers

**Comment by dbrgn** [comment]
It appears that the security headers don't include CORS. I'll add a custom header.

@gidsi when setting dependencies, can I also run a role without also running the dependencies? (I don't want to run the docker, watchtower etc roles every time I change a validator config.)

**Comment by rnestler** [comment]
> @gidsi when setting dependencies, can I also run a role without also running the dependencies? (I don't want to run the docker, watchtower etc roles every time I change a validator config.)

What's the problem with that? Since these roles didn't change they should just report OK for everything and do nothing which takes at most a few seconds.

**Comment by gidsi** [comment]
> If the roles have a lot of tasks it may still take 20-30 seconds (especially the docker module takes a while to check whether there are image updates, IIRC).

Shouldn't we solve that problem by using tags? I mean i totaly get where you coming from here, but (in case we have to) but it hides the fact that it has these dependencies and in case we just put the dependencies in the playbook before someone has actually to remember which roles are dependent on what when we're trying to partially refactor something.

**Comment by gidsi** [comment]
> > Shouldn't we solve that problem by using tags?
> 
> Can you explain what you mean with that? It will probably answer this question:
>
> > @gidsi when setting dependencies, can I also run a role without also running the dependencies?

I completly understand that you don't want to fire up the whole playbook to just change one config file, so i would add a tag for that task specifically and register a handler to restart the service itself, instead of running the whole role + dependencies.

**Comment by dbrgn** [comment]
@gidsi role updated

**Pull request merged**
