### PR TITLE
Add my SSH public key

### PR DESCRIPTION
**Pull request by dbrgn**
@gidsi is this how to add a key? Or do other files need to be modified as well?

How do I get this deployed?

### CODE REVIEW

**Comment by gidsi** [comment]
Unfortunately you would need to add the key id here too:
https://github.com/SpaceApi/provisioning/blob/master/nodes/prod.tfvars
https://github.com/SpaceApi/provisioning/blob/master/nodes/dev.tfvars

But as i said, that would lead to a complete rebuild of the VMs. 

We should add ssh key handling to ansible because terraform basically just needs them for the initial bootstrap.

**Comment by rnestler** [comment]
> But as i said, that would lead to a complete rebuild of the VMs.

Why would this lead to a complete rebuild? Doesn't make much sense to me. And even if it does, we could probably add our keys to the dev.tfvars right? Because there it isn't a problem if it gets rebuilt, right?

**Comment by gidsi** [comment]
> > But as i said, that would lead to a complete rebuild of the VMs.
> 
> Why would this lead to a complete rebuild? Doesn't make much sense to me. And even if it does, we could probably add our keys to the dev.tfvars right? Because there it isn't a problem if it gets rebuilt, right?

Hetzner doesn't support adding keys trough the api afterwards. 

Rebuilding isn't a real problem, but leads to a short downtime (VM gets destroyed and recreated, last time it took around 12 minutes)

**Comment by dbrgn** [comment]
> Unfortunately you would need to add the key id here too:

So how do I find out what the key ID of my key is?

**Comment by gidsi** [comment]
> > Unfortunately you would need to add the key id here too:
> 
> So how do I find out what the key ID of my key is?

You have to add your key first through the api, thats afaik the only way to obtain it. (It's really hacky, i'm sorry!)

**Comment by dbrgn** [comment]
Ok, how do I do that? :smile: And will that destroy the existing machines?

I just want to be able to log in somehow :slightly_smiling_face:

**Comment by gidsi** [comment]
superseded by #83

**Pull request closed without merging**
