### PR TITLE
Terraform

### PR DESCRIPTION
**Pull request by gidsi**
This is adding an automated way to deploy and destroy server. 

This is also fixing #24 and #25 

So far everything looks smooth in the dev environment, prod can't be tested without removing the old server and completely loosing spaceapi.net.

OS ist still debian but it doesn't seem to have the current problems (possible explanation is new docker packages and such).

Please tell me if you don't have the time to review and how you would like to continue :)

### CODE REVIEW

**Comment by rnestler** [comment]
@gidsi I don't really know terraform, but isn't it just an alternative to Ansible? So why not just do this with Ansible?

**Comment by gidsi** [comment]
> @gidsi I don't really know terraform, but isn't it just an alternative to Ansible? So why not just do this with Ansible?
@rnestler 

They have similarity's i would say, both projects use configuration files to communicate with a variety of interfaces using plugins and are used to automate things.

Ansible is widely used to provision running servers and orchestrate them, terraform is usually used to create vm's using the providers api. Terraform has e.g. a focus on in which order your resources should be created (because it know about the dependencies) and ansible has a bigger focus to do everything you can do on a shell. And you can even let terraform run from ansible and vice versa.

Here is a nice talk about the differences and similarity's:
https://www.hashicorp.com/resources/ansible-terraform-better-together

**Comment by dbrgn** [comment]
I'm wondering if we're not overengineering this. Does this setup start up multiple cloud servers in the Hetzner cloud?

Why do we need multiple servers and orchestration tools in order to serve a single static JSON file and a dozen static HTML files? :slightly_smiling_face: 

I know that automation has advantages, but complexity has huge downsides once you want other people to be able to take over the project at any time. I would really like it if our setup would be "run this docker container and set those env vars and you're good to go".

**Comment by gidsi** [comment]
> I'm wondering if we're not overengineering this. Does this setup start up multiple cloud servers in the Hetzner cloud?

No, it doesn't. It deploys basically the same server we have right now.

What it is giving us the ability to deploy the same setup as a testing environment to check changes (e.g. new debian, raising versions of something etc.) and destroy and redeploy the live server (while keeping the ip and a persistent volume with our data).

We've automated the process that happened before, no one beside me knew and had access too :)

> ... to serve a single static JSON file and a dozen static HTML files? slightly_smiling_face

That's more tricky and i would say also quite polemic i would say.
And i don't think we do just that. I think this is the absolute minimum we have to do, but there is so much more we're doing and should do.

For instance:
We're changing the schema and taking care of the directory and we're also trying to get more people involved.

> I know that automation has advantages, but complexity has huge downsides once you want other people to be able to take over the project at any time. I would really like it if our setup would be "run this docker container and set those env vars and you're good to go".

Yeah, keeping complexity low is one of my primary targets and this is not adding any, it adds documentation that wasn't there before.

**Comment by rnestler** [comment]
@gidsi I'm not really able to review this, because I'd need to learn a lot about teraform first. It would be nice if we could organize a meetup where you could walk us through it :slightly_smiling_face: 
Can be either at an event, a separate physical meetup or some screen-cast session (where you can see my screen and guide me through what I should do for example)

**Comment by gidsi** [comment]
> @gidsi I'm not really able to review this, because I'd need to learn a lot about teraform first. It would be nice if we could organize a meetup where you could walk us through it slightly_smiling_face
> Can be either at an event, a separate physical meetup or some screen-cast session (where you can see my screen and guide me through what I should do for example)

We could do that on Tuesday 9th April 19:30CEST, half an hour before the telco, or as part of it or after.

I would prefer before but don't have strong opinions.

**Pull request merged**
