### PR TITLE
New-style calling of apt and pip modules

### PR DESCRIPTION
**Pull request by dbrgn**
The old approach is deprecated.

### CODE REVIEW

**Comment by rnestler** [comment]
Which minimum Ansible version does this require?

**Comment by dbrgn** [comment]
I'm not sure :slightly_smiling_face:

**Comment by rnestler** [comment]
> I'm not sure slightly_smiling_face

Well, read the documentation and update the CI accordingly :wink:

**Comment by dbrgn** [comment]
Ah, sorry, I did not realize that this question was about the CI failure.

**Comment by dbrgn** [comment]
Hehe, in CI we always install the latest ansible version. The reason for the failure is a syntax error, some lines were indented too much :laughing:

**Comment by dbrgn** [comment]
@rnestler fixed.

**Pull request merged**
